apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= # Defining creds for MongoDb    # Creds: username
  mongo-root-password: cGFzc3dvcmQ= # Defining creds for MongoDb    # Creds: password
  mongo-express-username: YWRtaW4= # Defining creds for MongoDb Express for browser login # Creds: admin
  mongo-express-password: YWRtaW4= # Defining creds for MongoDb Express for browser login # Creds: admin
