apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson: # Base64 version of the .docker/config.json file
type: kubernetes.io/dockerconfigjson

# minikube cp minikube:/home/docker/.docker/config.json <Local_System_Path>
