kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 2
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: nginx
      version: v01
  template:
    metadata:
      labels:
        app: nginx
        version: v01
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: nginx
        image: 474668421704.dkr.ecr.eu-north-1.amazonaws.com/bkob/demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
