kind: Deployment
apiVersion: apps/v1
metadata:
  name: mosquitto
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app: mosquitto
      version: v01
  template:
    metadata:
      labels:
        app: mosquitto
        version: v01
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
